/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lkl_demos_jni_TestNative */

#ifndef _Included_cn_lkl_demos_jni_TestNative
#define _Included_cn_lkl_demos_jni_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lkl_demos_jni_TestNative
 * Method:    helloWord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_lkl_demos_jni_TestNative_helloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
